---
title: "Data Wrangling"
output: html_document
date: "2023-06-22"
---

# Some setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Loading required libraries
pacman::p_load(tidyverse, rjson, DEoptim, doParallel, readr, here, jsonlite, modi, gplots)

# Importing external R script with model fitting code
source("./C_modelfittingCode/models.R")

# Import verbose functions
source("observation_functions.R")

```

# Importing data, creating variables, and summary tables

## Functions for data

```{r}
library(tidyverse)
library(readr)
library(dplyr)

# Function to load data and add a 'group' column
load_data <- function(file_path, group_name) {
  data <- read_csv(file = file_path)
  data <- data %>% mutate(group = group_name)
  return(data)
}

# Function to calculate max value for a given group and column
max_value <- function(data, group_name, column_name) {
  max_value <- max(data[data$group == group_name, column_name], na.rm = TRUE)
  return(max_value)
}

# Function to increase a column's values for a given group
increase_value <- function(data, group_name, column_name, increase_by) {
  data[data$group == group_name, column_name] <- data[data$group == group_name, column_name] + increase_by
  return(data)
}

# Function to calculate color class
calc_color_class <- function(points) {
  color_class <- case_when(
    points < -60 ~ -7,
    points >= -60 & points < -40 ~ -5,
    points >= -40 & points < -20 ~ -3,
    points >= -20 & points < 0 ~ -1,
    points >= 0 & points < 20 ~ 1,
    points >= 20 & points < 40 ~ 3,
    points >= 40 & points < 60 ~ 5,
    points >= 60 & points < 150 ~ 7,
    points >= 150 ~ 9
  ) / 2
  return(color_class)
}

# Function to process data

process_data <- function(data) {
  # Remove rows where 'cell', 'x', or 'y' are NA
  data <- data %>% filter(!is.na(cell), !is.na(x), !is.na(y))
  
  # Sort the data by player and round
  data <- data %>% arrange(player, round)
  
  # Group by player and round, then arrange by unique_rounds and trial
  # Create a new variable 'similar' that checks if the current cell is the same as the previous cell
  data <- data %>%
    group_by(player, round) %>%
    arrange(unique_rounds, trial) %>%
    mutate(similar = lag(cells) == cells)
  
  # Arrange by unique_rounds and trial in descending order
  # Create a new variable 'length_exploitation' that finds the first instance where 'similar' is FALSE
  data <- data %>%
    arrange(unique_rounds, desc(trial)) %>%
    mutate(length_exploitation = match(FALSE, similar, nomatch = max(trial)) - 1)
  
  # Group by player and unique_rounds, then arrange by trial
  # Create a new variable 'length_exploration' that finds the first instance where a cell is duplicated
  data <- data %>%
    ungroup() %>%
    group_by(player, unique_rounds) %>%
    arrange(trial) %>%
    mutate(length_exploration = match(TRUE, duplicated(cells), nomatch = max(trial)) - 1)
  
  # Arrange by unique_rounds and trial in descending order
  # Group by player and unique_rounds
  # Create new variables 'threshold_accumulation' and 'threshold_exploitation' based on 'points' at certain trials
  data <- data %>%
    ungroup() %>%
    arrange(unique_rounds, desc(trial)) %>%
    group_by(player, unique_rounds) %>%
    mutate(
      threshold_accumulation = points[match(length_exploitation + 1, trial)],
      threshold_exploitation = points[match(25 - length_exploitation, trial)]
    )
  
  # Create a new variable 'phases' that categorizes each trial into a phase
  # If 'round_gem_found' is not NA and 'trial' is greater than 'round_gem_found', replace 'phases' with "gem"
  data <- data %>%
    ungroup() %>%
    mutate(
      phases = case_when(
        trial <= length_exploration ~ "exploration",
        trial > length_exploration & trial < (25 - length_exploitation + 1) ~ "accumulation",
        trial >= (25 - length_exploitation) ~ "exploitation",
        TRUE ~ "other" # Any other case
      ),
      phases = if_else(!is.na(round_gem_found) & trial > round_gem_found, "gem", phases)
    )
  
  # Rearrange data in ascending order by player, unique_rounds and trial before computing visited_this_round
  # Group by player, unique_rounds and cells to compute visited_this_round
  data <- data %>%
    arrange(player, unique_rounds, trial) %>%
    group_by(player, unique_rounds, cells) %>%
    mutate(visited_this_round = cumsum(duplicated(cells)))

  # Create new variable 'known_cell' that checks if a cell has been visited in the current round
  data <- data %>%
    ungroup() %>%
    mutate(known_cell = visited_this_round > 0)

  # Replace 'threshold_accumulation' and 'threshold_exploitation' values greater than 180 with NA
  data <- data %>%
    mutate(
      threshold_accumulation = if_else(threshold_accumulation > 180, NA, threshold_accumulation),
      threshold_exploitation = if_else(threshold_exploitation > 180, NA, threshold_exploitation)
    )

  # Calculate color class for points
  data <- data %>% mutate(color_class = calc_color_class(points))

  # Finally, rearrange data in ascending order by player, unique_rounds and trial
  data <- data %>% arrange(player, unique_rounds, trial)

  return(data)
}

# Function to create summary data
create_summary_data <- function(data) {
  summary_data <- data %>%
    select(unique_rounds, player, round, length_exploitation, length_exploration, threshold_accumulation, threshold_exploitation) %>%
    distinct() %>%
    mutate(
      trial_exploitation = 26 - length_exploitation,
      trial_accumulation = length_exploration + 1,
      length_accumulation = trial_exploitation - trial_accumulation
    ) %>%
    left_join(
      data %>% 
        select(unique_rounds, player, color_class) %>%
        distinct(),
      by = c("unique_rounds", "player")
    ) %>%
    mutate(
      threshold_accumulation_color_class = calc_color_class(threshold_accumulation),
      threshold_exploitation_color_class = calc_color_class(threshold_exploitation)
    )
  return(summary_data)
}
```

## Process of creating data

```{r}
# Load the data
explore_data <- load_data("data/social/data_social_coord.csv", "adults")
explore_data_adolescence <- load_data("data/social/data_social_coord_schoolbactch_1.csv", "adolescents")

# Merge the data frames
data <- bind_rows(explore_data, explore_data_adolescence)

# Find the maximum 'unique_rounds' and 'player' in the adolescent sample
max_unique_rounds_adolescents <- max_value(data, "adolescents", "unique_rounds")
max_player_adolescents <- max_value(data, "adolescents", "player")

# Increase 'unique_rounds' and 'player' for adults by the maximum 'unique_rounds' in the adolescent sample
data <- increase_value(data, "adults", "unique_rounds", max_unique_rounds_adolescents)
data <- increase_value(data, "adults", "player", max_player_adolescents)

# Process the data
data <- process_data(data)

# Create summary data
summary_data <- create_summary_data(data)

# Viewing the summary data and main data
head(summary_data)
head(data)
```

# Observational tests:

## Functions heatmaps

```{r}


## For heat maps functions

get_first_trials <- function(data, turns_range) {
  first_trials <- data[data$trial %in% turns_range, c("player","trial","unique_rounds","cell","x","y")]
  first_trials_counts <- as.data.frame(table(first_trials$cell))
  first_trials_counts$cell <- as.numeric(as.character(first_trials_counts$Var1))
  first_trials_counts$x <- first_trials_counts$cell %% 8
  first_trials_counts$y <- first_trials_counts$cell %/% 8
  first_trials_counts$rel_Freq <- first_trials_counts$Freq / sum(first_trials_counts$Freq) * nrow(first_trials_counts)
  return(first_trials_counts)
}

get_weighted_metrics <- function(first_trials_counts) {
  w_avg_x <- weighted.mean(first_trials_counts$x - 3.5, first_trials_counts$Freq)
  w_avg_y <- weighted.mean(first_trials_counts$y - 3.5, first_trials_counts$Freq)
  w_std_x <- sqrt(weighted.var(first_trials_counts$x - 3.5, first_trials_counts$Freq))
  w_std_y <- sqrt(weighted.var(first_trials_counts$y - 3.5, first_trials_counts$Freq))
  return(list(w_avg_x = w_avg_x, w_avg_y = w_avg_y, w_std_x = w_std_x, w_std_y = w_std_y))
}

get_matrices <- function(first_trials_counts) {
  mat <- matrix(0, nrow = 8, ncol = 8)
  for(i in 1:nrow(first_trials_counts)) {
    mat[first_trials_counts$y[i] + 1, first_trials_counts$x[i] + 1] <- first_trials_counts$Freq[i]
  }
  return(mat)
}

get_rel_matrix <- function(first_trials_counts) {
  rel_mat <- matrix(0, nrow = 8, ncol = 8)
  for(i in 1:nrow(first_trials_counts)) {
    rel_mat[first_trials_counts$y[i] + 1, first_trials_counts$x[i] + 1] <- first_trials_counts$rel_Freq[i]
  }
  rel_mat <- round(rel_mat, 2)
  return(rel_mat)
}

get_quadrant_freq <- function(mat) {
  quadrant_freq <- c(
    Q1 = sum(mat[1:4, 5:8]),
    Q2 = sum(mat[1:4, 1:4]),
    Q3 = sum(mat[5:8, 1:4]),
    Q4 = sum(mat[5:8, 5:8])
  )
  return(quadrant_freq)
}

get_chisq_test_result <- function(quadrant_freq) {
  chisq_test_result <- chisq.test(quadrant_freq)
  return(chisq_test_result)
}

get_first_move_metrics <- function(w_avg_x, w_avg_y, w_std_x, w_std_y) {
  first_move_metrics <- data.frame(
    Metric = c("avg x", "avg y", "std x", "std y"),
    Value = c(round(w_avg_x, 4), round(w_avg_y, 4), round(w_std_x, 3), round(w_std_y, 3))
  )
  return(first_move_metrics)
}

generate_heatmap <- function(mat, cellnote, title) {
  heatmap.2(mat, trace = "none", dendrogram = "none", Rowv = FALSE, Colv = FALSE,
            margins = c(5, 5), cellnote = cellnote, notecex = 1, notecol = "black",
            main = title)
}

get_joined_data <- function(data, summary_data) {
  joined_data <- data %>%
    left_join(summary_data, by = c("unique_rounds", "player", "round")) %>%
    group_by(unique_rounds) %>%
    filter(trial < trial_exploitation)
  return(joined_data)
}

get_new_data <- function(joined_data) {
  new_data <- joined_data %>%
    count(player, cell) %>%
    group_by(player) %>%
    mutate(rel_Freq = n / sum(n),
           Var1 = as.character(cell),
           x = cell %% 8,
           y = cell %/% 8)
  return(new_data)
}

get_first_trials_counts <- function(new_data) {
  first_trials_counts <- new_data %>%
    group_by(cell, x, y) %>%
    summarise(rel_Freq = sum(rel_Freq), .groups = "drop") %>%
    mutate(rel_Freq = (rel_Freq / n_distinct(new_data$player)) * 64)
  return(first_trials_counts)
}

```

# Heat maps 

## for the first move:

```{r}
# Select data from the first trials only and count cell frequencies
first_trials_counts <- get_first_trials(data, 1)

# Compute weighted means and standard deviations
weighted_metrics <- get_weighted_metrics(first_trials_counts)
w_avg_x <- weighted_metrics$w_avg_x
w_avg_y <- weighted_metrics$w_avg_y
w_std_x <- weighted_metrics$w_std_x
w_std_y <- weighted_metrics$w_std_y

# Create matrices for frequencies and relative frequencies
mat <- get_matrices(first_trials_counts)

# Calculate quadrant frequencies
quadrant_freq <- get_quadrant_freq(mat)
print(round(quadrant_freq,3))

# Chi-square test for goodness-of-fit
chisq_test_result <- get_chisq_test_result(quadrant_freq)

# Print the result
print(chisq_test_result)

# Print first move metrics
first_move_metrics <- get_first_move_metrics(w_avg_x, w_avg_y, w_std_x, w_std_y)
print(first_move_metrics)

# Create heatmaps
generate_heatmap(mat, mat, "First Trial for each Round.\nCell Selection, Absolute Numbers")
generate_heatmap(mat, mat, "First Trial for each Round.\nCell Selection, Relative Numbers")
```

## Heat map for all moves:

```{r}
# Define the range of trials to consider
turns_range <- 1:25

# Select data from the first trials only and count cell frequencies
first_trials_counts <- get_first_trials(data, turns_range)

# Compute weighted means and standard deviations
weighted_metrics <- get_weighted_metrics(first_trials_counts)
w_avg_x <- weighted_metrics$w_avg_x
w_avg_y <- weighted_metrics$w_avg_y
w_std_x <- weighted_metrics$w_std_x
w_std_y <- weighted_metrics$w_std_y

# Create matrices for frequencies and relative frequencies
mat <- get_matrices(first_trials_counts)
rel_mat <- get_rel_matrix(first_trials_counts)

# Calculate quadrant frequencies
quadrant_freq <- get_quadrant_freq(mat)
print(round(quadrant_freq,3))

# Chi-square test for goodness-of-fit
chisq_test_result <- get_chisq_test_result(quadrant_freq)
print(chisq_test_result)

# Print first move metrics
first_move_metrics <- get_first_move_metrics(w_avg_x, w_avg_y, w_std_x, w_std_y)
print(first_move_metrics)

# Create heatmaps
generate_heatmap(mat, mat, "First 25 Trials for each Round.\nCell Selection, Absolute Numbers")
generate_heatmap(rel_mat, rel_mat, "First 25 Trials for each Round.\nCell Selection, Relative Numbers")
```

## Functions for heat map without exploitation

```{r}
# Function to calculate length_accumulation
calc_length_accumulation <- function(data) {
  data <- data %>%
    group_by(player, unique_rounds) %>%
    mutate(
      trial_exploitation = 26 - length_exploitation,
      trial_accumulation = length_exploration + 1,
      length_accumulation = trial_exploitation - trial_accumulation
    ) %>%
    ungroup()
  return(data)
}

# Function to join data with summary_data and filter the trials
join_and_filter_data <- function(data, summary_data) {
  joined_data <- data %>%
    left_join(summary_data, by = c("unique_rounds", "player", "round")) %>%
    group_by(player) %>%
    filter(data$trial < data$trial_exploitation)
  return(joined_data)
}

# Function to create new data with relative frequencies
create_new_data <- function(joined_data) {
  new_data <- joined_data %>%
    count(player, cell) %>%
    group_by(player) %>%
    mutate(rel_Freq = n / sum(n),
           Var1 = as.character(cell),
           x = cell %% 8,
           y = cell %/% 8)
  return(new_data)
}

# Function to calculate first_trials_counts
calc_first_trials_counts <- function(new_data) {
  first_trials_counts <- new_data %>%
    group_by(cell, x, y) %>%
    summarise(rel_Freq = sum(rel_Freq), .groups = "drop") %>%
    mutate(rel_Freq = (rel_Freq / n_distinct(new_data$player)) * 64)
  return(first_trials_counts)
}

# Function to create a matrix from first_trials_counts
create_matrix <- function(first_trials_counts) {
  mat <- matrix(0, nrow = 8, ncol = 8)
  for(i in 1:nrow(first_trials_counts)) {
    mat[first_trials_counts$y[i] + 1, first_trials_counts$x[i] + 1] <- first_trials_counts$rel_Freq[i]
  }
  mat <- round(mat, 3)
  return(mat)
}

# Function to calculate quadrant frequencies
calc_quadrant_freq <- function(mat) {
  quadrant_freq <- c(
    Q1 = sum(mat[1:4, 5:8]),
    Q2 = sum(mat[1:4, 1:4]),
    Q3 = sum(mat[5:8, 1:4]),
    Q4 = sum(mat[5:8, 5:8])
  )
  return(round(quadrant_freq, 3))
}

# Function to perform Chi-Square Test
perform_chisq_test <- function(quadrant_freq) {
  chisq_test_result <- chisq.test(quadrant_freq)
  return(chisq_test_result)
}

# Function to print sum of relative frequencies
print_rel_freq_sum <- function(first_trials_counts) {
  print(sum(first_trials_counts$rel_Freq))
}
```

## Heat map without exploitation

```{r}
# Calculate length_accumulation in the data dataframe
data <- calc_length_accumulation(data)

# Join data with summary_data and filter the trials
joined_data <- get_joined_data(data, summary_data)

# Create the new dataframe with relative frequencies and group by player
new_data <- create_new_data(joined_data)

# Calculate sum of rel_Freq for each cell and then divide by total number of players
first_trials_counts <- calc_first_trials_counts(new_data)

# Initialize an 8x8 matrix and fill with relative frequencies
mat <- create_matrix(first_trials_counts)

# Calculate quadrant frequencies
quadrant_freq <- calc_quadrant_freq(mat)
print(quadrant_freq)

# Perform Chi-Square Test
chisq_test_result <- perform_chisq_test(quadrant_freq)
print(chisq_test_result)

# Generate heatmap
title <- paste("First Trial for each Round.","\n", "Cell Selection, Relative Numbers")
generate_heatmap(mat, mat, title)

# Print sum of relative frequencies, should be approximately 64 (8x8 grid)
print_rel_freq_sum(first_trials_counts)
```
